#!/usr/bin/env python3
"""Generates streams.h: tiny H.264 test clips (solid colour, 4 pictures) for the decoder probe.
Needs ffmpeg with libx264. The clips are split into access units at the AUD NAL units."""
import os, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
COLOR = "0x3080C0"          # R=0x30 G=0x80 B=0xC0: the probe checks a decoded pixel against it
CLIPS = [("s720", 1280, 720), ("s1080", 1920, 1080)]

def clip(name, w, h, tmp):
    out = os.path.join(tmp, name + ".h264")
    subprocess.run(["ffmpeg", "-loglevel", "error", "-y", "-f", "lavfi", "-i", f"color=c={COLOR}:size={w}x{h}:rate=25",
                    "-frames:v", "4", "-c:v", "libx264", "-profile:v", "high", "-pix_fmt", "yuv420p", "-bf", "0", "-refs", "1",
                    "-x264-params", "aud=1:keyint=4", "-f", "h264", out], check=True)
    es = open(out, "rb").read()
    starts = [i for i in range(len(es) - 4) if es[i:i + 3] == b"\0\0\1" and (es[i + 3] & 0x1F) == 9]
    starts = [s - 1 if s > 0 and es[s - 1] == 0 else s for s in starts]   # keep 4-byte start codes whole
    bounds = starts + [len(es)]
    return [es[a:b] for a, b in zip(bounds, bounds[1:])]

def main():
    tmp = tempfile.mkdtemp(prefix="probe_")
    lines = ["/* Generated by make_streams.py - do not edit. Solid colour " + COLOR + ", 4 pictures each. */",
             "#include <stdint.h>", "#include <stddef.h>",
             "typedef struct { const uint8_t *data; size_t size; } ProbeAu;"]
    for name, w, h in CLIPS:
        aus = clip(name, w, h, tmp)
        for k, au in enumerate(aus):
            body = ",".join(str(b) for b in au)
            lines.append(f"static const uint8_t {name}_au{k}[{len(au)}] = {{{body}}};")
        lines.append(f"static const ProbeAu {name}_aus[] = {{" + ",".join(f"{{{name}_au{k}, sizeof {name}_au{k}}}" for k in range(len(aus))) + "};")
        lines.append(f"#define {name.upper()}_N {len(aus)}")
        print(name, w, h, len(aus), "units,", sum(map(len, aus)), "bytes", file=sys.stderr)
    open(os.path.join(HERE, "streams.h"), "w").write("\n".join(lines) + "\n")

main()
